spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sdp_gateway_new
    username: xxxx
    password: xxxx
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: select 1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.ssgh.sdpgateway.mtls.mapper: debug
    com.baomidou.mybatisplus: debug

mtls:
  controller-ip: xxxx #控制器 MTLS ip 地址
  controller-port: xxxx #控制器 MTLS 端口号
  gateway-ip: xxxx #网关 MTLS ip地址
  gateway-port: xxxx #网关 MTLS 端口号
  len-field-length: 4

spa:
  controller-ip: xxxx #控制器 SPA ip 地址
  controller-port: xxxx #控制器 SPA 端口
  gateway-ip: xxxx #网关 SPA IP地址
  gateway-port: xxxx #网关 SPA 端口号
